name: Build and Test MAUI Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build WeightWizard_test.csproj -c Release

      - name: Test application
        run: dotnet test WeightWizard_test.test.csproj
