on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  PROJECT_PATH: "WeightWizard/WeightWizard.csproj"

jobs:
  
  # MAUI Android Build
  build-android:
    runs-on: windows-latest
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Cache MAUI Android Build
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/AppData/Local/Android/Sdk/ndk/*
            ~/AppData/Local/Android/Sdk/ndk-bundle/*
          key: ${{ runner.os }}-maui-android-build-${{ hashFiles(env.PROJECT_PATH) }}-${{ hashFiles('**/android*.csproj') }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Cache MAUI Workload
        uses: actions/cache@v2.1.6
        with:
          path: ~/.nuget/packages/xamarin.maui.*
          key: ${{ runner.os }}-maui-workload-${{ hashFiles(env.PROJECT_PATH) }}

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build MAUI Android
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-android --no-restore

      - name: Cache MAUI Android Output
        uses: actions/cache@v2.1.6
        with:
          path: WeightWizard/bin/Release/net7.0-android/
          key: ${{ runner.os }}-maui-android-output-${{ hashFiles(env.PROJECT_PATH) }}

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: WeightWizard-android-ci-build
          path: WeightWizard/bin/Release/net7.0-android/*Signed.a*
